//Author: Andreea

#ifndef MessageTypes_E
#define MessageTypes_E

enum MessageTypes_E
{
	NO_MESSAGE ,
	ALL_GOOD ,
	WRITE_TO_FILE ,
	WALLET_ALREADY_EXISTS ,
	CREATE_NAME_MISSING ,
	CREATE_INITIAL_AMMOUNT_INVALID ,
	PATH_DOES_NOT_EXIST ,
	CREATE_WALLET_MESSAGE ,
	AMOUNT_NOT_POSITIVE_SPEND ,
	AMOUNT_NOT_POSITIVE_INCOME ,
	NO_DEFAULT_WALLET ,
	COULD_NOT_OPEN_CONFIG ,
	SHOULD_BE_POSITIVE ,
	NO_AMOUNT_SPECIFIED ,
	COULD_NOT_OPEN_PATH ,
	COULD_NOT_OPEN_PATH_BALANCE ,
	INVALID_PARAMETER ,
	INVALID_COMMAND , 
	BALANCE_CATEGORY , 
	BALANCE_ALL_WALLET , 
	NO_TRANSACTION_WITH_CATEGORY , 
	NOT_A_VALID_CONFIG_VALUE , 
	INCOME_REGISTERED , 
	SPENDING_REGISTERED , 
	SET_DEFAULT_WALLET , 
	NO_OUTPUT_CONFIGURED , 
};